//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab2.HorasMediasService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HorasMediasService.horasMediasSoap")]
    public interface horasMediasSoap {
        
        // CODEGEN: Generating message contract since element name asignatura from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHorasMedias", ReplyAction="*")]
        Lab2.HorasMediasService.getHorasMediasResponse getHorasMedias(Lab2.HorasMediasService.getHorasMediasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHorasMedias", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab2.HorasMediasService.getHorasMediasResponse> getHorasMediasAsync(Lab2.HorasMediasService.getHorasMediasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHorasMediasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHorasMedias", Namespace="http://tempuri.org/", Order=0)]
        public Lab2.HorasMediasService.getHorasMediasRequestBody Body;
        
        public getHorasMediasRequest() {
        }
        
        public getHorasMediasRequest(Lab2.HorasMediasService.getHorasMediasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getHorasMediasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string asignatura;
        
        public getHorasMediasRequestBody() {
        }
        
        public getHorasMediasRequestBody(string asignatura) {
            this.asignatura = asignatura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHorasMediasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHorasMediasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab2.HorasMediasService.getHorasMediasResponseBody Body;
        
        public getHorasMediasResponse() {
        }
        
        public getHorasMediasResponse(Lab2.HorasMediasService.getHorasMediasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getHorasMediasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getHorasMediasResult;
        
        public getHorasMediasResponseBody() {
        }
        
        public getHorasMediasResponseBody(int getHorasMediasResult) {
            this.getHorasMediasResult = getHorasMediasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface horasMediasSoapChannel : Lab2.HorasMediasService.horasMediasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class horasMediasSoapClient : System.ServiceModel.ClientBase<Lab2.HorasMediasService.horasMediasSoap>, Lab2.HorasMediasService.horasMediasSoap {
        
        public horasMediasSoapClient() {
        }
        
        public horasMediasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public horasMediasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public horasMediasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public horasMediasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab2.HorasMediasService.getHorasMediasResponse Lab2.HorasMediasService.horasMediasSoap.getHorasMedias(Lab2.HorasMediasService.getHorasMediasRequest request) {
            return base.Channel.getHorasMedias(request);
        }
        
        public int getHorasMedias(string asignatura) {
            Lab2.HorasMediasService.getHorasMediasRequest inValue = new Lab2.HorasMediasService.getHorasMediasRequest();
            inValue.Body = new Lab2.HorasMediasService.getHorasMediasRequestBody();
            inValue.Body.asignatura = asignatura;
            Lab2.HorasMediasService.getHorasMediasResponse retVal = ((Lab2.HorasMediasService.horasMediasSoap)(this)).getHorasMedias(inValue);
            return retVal.Body.getHorasMediasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab2.HorasMediasService.getHorasMediasResponse> Lab2.HorasMediasService.horasMediasSoap.getHorasMediasAsync(Lab2.HorasMediasService.getHorasMediasRequest request) {
            return base.Channel.getHorasMediasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab2.HorasMediasService.getHorasMediasResponse> getHorasMediasAsync(string asignatura) {
            Lab2.HorasMediasService.getHorasMediasRequest inValue = new Lab2.HorasMediasService.getHorasMediasRequest();
            inValue.Body = new Lab2.HorasMediasService.getHorasMediasRequestBody();
            inValue.Body.asignatura = asignatura;
            return ((Lab2.HorasMediasService.horasMediasSoap)(this)).getHorasMediasAsync(inValue);
        }
    }
}
